meta_product_name: "Netherlands Locals Osusume"
meta_title: "Netherlands Locals Osusume - Discover Hidden Gems Recommended by Japanese Locals"
meta_description: "Netherlands Locals Osusume helps you find the best places to visit in the Netherlands, recommended by Japanese locals. Avoid tourist traps and discover hidden spots not mentioned in guidebooks."
meta_image: "meta_image.png" # should exist in `app/assets/images/`
twitter_account: "@Ry0330334341" # required for Twitter Cards
